#!/bin/bash

echo "Post installation"
echo "Spawn process to install ppa when dpkg over"

(
  while [ 1 ] ; do
    sleep 1
    if pgrep -ox dpkg &> /dev/null ; then
      echo " " # not over
    else
      echo " Running post process DPKG"
      sudo add-apt-repository -y ppa:chris-lea/redis-server
      sudo apt install -y redis-tools
      exit 0
    fi
   done;
)&

exit 0
